    //premetive data type->string,number,Boolean,Null,Undefined,Bigint,Symbol
    //Non primitive data type-> Array,object
    // string
    let name3="Arjun"
    console.log(name3)
    console.log(typeof(name3));
    //num
    let num=42
    console.log(num);
    console.log(typeof(num));
    //boolean
    let pass=true
    console.log(pass);
    //undefined
    let name;
    console.log(name);
    console.log(typeof(name));
    //null
    let name2=null
    console.log(name2);
    console.log(typeof(name2));
    // symbol
    let id=Symbol("id");
    console.log(id);
    
    
    
    
    
    
    
    
    
    
    